
---
title: "Final Project"
author: "Mitchell Kazin, Adam VanGorp, Shivam Vashi, and Mathew P"
date: "11/19/2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
data = read.csv("consolidated_weather_V03.csv")
head(data)
library(ggplot2)
library(class)
```

```{r}
################### Visibility Exploration
### summary statistics
data <- mutate_at(data, vars(17:17),as.numeric)
summary(data$vis)

### frequency of sightings by visibility
dat <- as.data.frame(table(data$vis))
dat

### histogram
ggplot(data, aes(x=vis)) + geom_histogram() + ggtitle("Count of UFO Sightings by Visibility") + xlab("Visibility") + ylab("Count of UFO Sightings")

### scatter plot
ggplot(dat, aes(x=Var1, y=Freq)) + geom_point()

scatter.smooth(x=dat$Var1, y=dat$Freq, main="2")

### correlation
dat <- mutate_at(dat, vars(1:1),as.numeric)
cor(dat$Var1, dat$Freq)

### linear regression 
linmod <- lm(Freq ~ Var1, data = dat)
linmod
summary(linmod)
summary(linmod)$r.squared

### Weather KNN Model
weather = data[,-c(1,2,3,5,6,7,8,9,13,14,17,21,26,27)]
weather = weather[complete.cases(weather),]
n = nrow(weather)
n_train = floor(n*.5)
index_train <- sample(1:n,n_train,replace=FALSE)
train = weather[index_train,-1]
test = weather[-index_train,-1]
train_target = weather[index_train,1]
test_target = weather[-index_train,1]
loops = 100
k_data = data.frame("k" = rep(0, loops),"accuracy" = rep(0,loops))

# Runs KNN 100 times to select best k-value
for(i in c(1:loops)){
  fit = knn(train, test, cl=train_target, k=i)
  tab = table(fit,test_target)
  accuracy <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}
  acc = accuracy(tab)
  k_data[i,1] = i
  k_data[i,2] = acc
}
head(k_data)
ggplot(k_data, aes(k, accuracy)) + geom_line()
#citation for accuracy function: https://towardsdatascience.com/k-nearest-neighbors-algorithm-with-examples-in-r-simply-explained-knn-1f2c88da405c

# Plot accuracy of models for each k-value
ggplot(k_data, aes(k, accuracy)) + geom_line() + ggtitle("Test Data Accuracy vs K-Value")

###Spatial Mapping and Airplane Data
us_states <- map_data("state")
head(us_states)
head(state.x77)
UFO = read.csv("consolidated_weather_V03.csv")
planes = read.csv("faa_registration.csv")
loc <- state.name[match(UFO$state,state.abb)]
planeLoc <- state.name[match(planes$STATE,state.abb)]
planeLoc <- table(planeLoc)
head(planeLoc)
loc <- table(loc)
barplot(loc, main = "Count of UFO sightings in the US", xlab = "State", ylab = "Count", las = 2)
barplot(planeLoc, main = "Count of plane sightings in the US", xlab = "State", ylab = "Count", las = 2)
loc <- as.data.frame(loc)
planeLoc <- as.data.frame(planeLoc)
names(loc) = c("region", "freq")
names(planeLoc) = c("region", "planeFreq")
loc$region <- tolower(loc$region)
planeLoc$region <- tolower(planeLoc$region)
head(planeLoc)
head(us_states)
ufo_sightings <- left_join(us_states, loc)
ufo_sightings <- left_join(ufo_sightings, planeLoc)
statepop <- as.data.frame(state.x77[,1])
statepop <- cbind(States = rownames(statepop), statepop)
names(statepop) <- c("region","population")
rownames(statepop) <- NULL
statepop$region <- tolower(statepop$region)
ufo_sightings <- left_join(ufo_sightings, statepop)
head(ufo_sightings)
p0 <- ggplot(data = ufo_sightings,
             mapping = aes(x = long, y = lat, group = group, fill = freq/population))

p1 <- p0 + geom_polygon(color = "gray90", size = 0.1) +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45)

p1<- p1 + labs(title = "Frequency of UFO Sightings")  + labs(fill = "Count")


p2 <- p1 + scale_fill_gradient(low = "white", high = "#CB454A") +
        labs(title = "Frequency of UFO Sightings") 
p2 + labs(fill = "Count")

p0 <- ggplot(data = ufo_sightings,
             mapping = aes(x = long, y = lat, group = group, fill = planeFreq/population))

p1 <- p0 + geom_polygon(color = "gray90", size = 0.1) +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45)

p1<- p1 + labs(title = "Frequency of plane Sightings")  + labs(fill = "Count")


p2 <- p1 + scale_fill_gradient(low = "white", high = "#00ff00") +
        labs(title = "Frequency of Plane Sightings") 
p2 + labs(fill = "Count")

ggplot(ufo_sightings, aes(x = freq, y = planeFreq)) + geom_point(size=2, shape=23) + geom_smooth(method='lm', formula= y~x) + ggtitle("UFO Sightings vs Plane Sightings") + xlab("UFO Sightings") + ylab("Plane Sightings")
ufo.lm = lm(freq ~ planeFreq, data=ufo_sightings) 
summary(ufo.lm)$r.squared 
t.test(ufo_sightings$freq, ufo_sightings$planeFreq)
```


